name: Kernel build CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jiu-xiao/kernel-docker:main

    steps:
    - uses: actions/checkout@v3

    - name: Set up link
      run: ln -s /usr/bin/python2.7 /usr/bin/python2

    - name: Install kernelSU
      run: curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

    - name: change full capacity
      run: sed -i '735s/.*/	*nom_cap_uah = ${{ vars.capacity }} *1000;/' drivers/power/supply/qcom/qpnp-fg-gen4.c

    - name: change design full capacity
      run: sed -i '28s/.*/	qcom,nom-batt-capacity-mah = < ${{ vars.capacity }} >;/' arch/arm64/boot/dts/vendor/qcom/fg-gen4-batterydata-alioth-FMT-4520mah.dtsi

    - name: config
      run: make LLVM=1 LLVM_IAS=1 O=out ARCH=arm64 SUBARCH=arm64 CC=clang LD=ld.lld vendor/alioth_defconfig

    - name: build
      run: make -j$(nproc) LLVM=1 LLVM_IAS=1 O=out ARCH=arm64 SUBARCH=arm64 CC=clang LD=ld.lld CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: pack kernel
      run: cp out/arch/arm64/boot/Image.gz ./F3-NoGravityKernel-1.5.0/ && find out/arch/arm64/boot/dts/vendor/qcom/ -name '*.dtb' -exec cat {} + >./F3-NoGravityKernel-1.5.0/dtb && cp out/arch/arm64/boot/dtbo.img ./F3-NoGravityKernel-1.5.0/ && cd F3-NoGravityKernel-1.5.0 && zip -r alioth-${{ vars.capacity }}.zip ./*

    - name: Create release
      run: echo "release_name=$(date +v%Y.%m.%d.vv%H.%M)" >> $GITHUB_ENV

    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.release_name }}
          release_name: Release ${{ env.release_name }}
          draft: false
          prerelease: false

    - name: Upload Kernel
      uses: actions/upload-release-asset@v1
      id: upload-kernel
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/F3-NoGravityKernel-1.5.0/alioth-${{ vars.capacity }}.zip
        asset_name: alioth-${{ vars.capacity }}.zip
        asset_content_type: application/zip
